### PR TITLE
Added a class to retrieve alarms

### PR DESCRIPTION
**Pull request by eliseomartelli**
I've added a class to retrieve alarms from the ghlocalapi. 
Alarms could be used for automations. It's a kinda nice thing to have. 

I've been using this: 
https://twitter.com/eliseomartelli/status/1037384524798349312

Thanks!

### CODE REVIEW

**Comment by eliseomartelli** [comment]
I'm getting the pylint warning "similar lines in two files". 
Is it possible to disable it?

**Comment by ludeeus** [comment]
Yeah... That one was stupid

**Comment by eliseomartelli** [comment]
Perfect. I'll add an example in ```example.py```

**Comment by eliseomartelli** [comment]
🎉 Yeah! I'm happy to know I've helped someone to feel a bit better!

**Comment by ludeeus** [comment]
<https://pypi.org/project/ghlocalapi/0.1.0/> This is now live 🎉

**Comment by eliseomartelli** [comment]
Nice!! 👏

**Pull request merged**
